# Generated by Django 4.2.5 on 2023-09-11 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['id'], 'verbose_name': 'Content', 'verbose_name_plural': 'Content'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['id'], 'verbose_name': 'Section', 'verbose_name_plural': 'Sections'},
        ),
    ]
