# Generated by Django 4.2.4 on 2023-09-15 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0002_alter_content_options_alter_section_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Test description')),
                ('question', models.TextField(blank=True, null=True, verbose_name='Question')),
                ('answer', models.CharField(blank=True, max_length=40, null=True, verbose_name='Answer')),
                ('test_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sections.section', verbose_name='Test section')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Tests',
                'ordering': ['test_section'],
            },
        ),
    ]
